content = open('src/app/page.tsx').read()
content = content.replace('Free shipping on orders over $50', 'Free shipping on orders over $45')
content = content.replace('Free shipping over $50', 'Free shipping over $45')
content = content.replace('free shipping on all orders over $50', 'free shipping on all orders over $45')
content = content.replace('Free shipping on all orders over $50', 'Free shipping on all orders over $45')
open('src/app/page.tsx', 'w').write(content)
print('Done!')
