content = open('src/app/layout.tsx').read()
content = content.replace("import PreorderBanner from './components/PreorderBanner';\n", "")
content = content.replace("          <PreorderBanner />\n", "")
open('src/app/layout.tsx', 'w').write(content)
print('Done!')
